version: "3"
services:
  today-timelapse:
    image: today-timelapse
    build: .
    command: /bluepi
    volumes:
      - /volume1/surveillance/bluepi:/bluepi
      - /var/services/homes/hombit/tmp:/output
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
